### PR TITLE
Fix rubocop errors

### PR DESCRIPTION
**Pull request by mattkasa**

### CODE REVIEW

**Comment by mattkasa** [comment]
@sbates I'm guessing I can't get any love on this PR? :)

**Comment by sbates** [comment]
I was too lazy to do the command line diff :)

**Comment by mattkasa** [comment]
There's a bunch of broken code in master now, otherwise I'd backmerge and get you a mergeable PR :)

**Comment by juliandunn** [comment]
closing now that training is over.

**Pull request closed without merging**
